In [1]:
COMMIT_ID = "__COMMIT__"

print("Hello World from Kaggle!")
print("Commit ID:", COMMIT_ID)

Hello World from Kaggle!
Commit ID: __COMMIT__

In [2]:
from pathlib import Path
from datetime import datetime
import os

now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

output_path = Path("/kaggle/working/runtime_log.txt")
output_path.write_text(
    f"Notebook ran successfully\n"
    f"Run time: {now}\n"
    f"Working dir: {os.getcwd()}\n"
)

print("Saved log to:", output_path)
print(output_path.read_text())

Saved log to: /kaggle/working/runtime_log.txt
Notebook ran successfully
Run time: 2026-03-30 16:08:15
Working dir: /kaggle/working

In [ ]:
import pandas as pd

df = pd.read_csv("/kaggle/input/titanic/train_and_test2.csv")
df.head(5)

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [ ]:
df_2 = pd.read_csv("/kaggle/input/job-salary-prediction-dataset/job_salary_prediction_dataset.csv")

df_2.head(5)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069